### ISSUE TITLE
Running dynamic_loot_filter.ahk after setup throws error

### ISSUE THREAD

**Issue by AndreWohnsland** [Apollys/PoEDynamicLootFilter#19] opened 2022-06-12 15:37 UTC
After running the setup script, the ahk file exits with an error:

```
Error at line 177.
Line Text: Switch prog
Error: this line does not contain a recognized action.
The program will exit
```

Using the latest version with win10, default system Python is 3.9.5. `python setup.py` worked without an error:

```
Welcome to the first-time setup script for PoE DLF!

Step 1: Checking python version...
Python version 3 detected, success!

Step 2: Set GUI toggle hotkey

Hotkey format: Ctrl = "^", Shift = "+", Alt = "!"
Example: Ctrl-Shift-a = "^+a"
Function keys may be typed as "F1" or "f1", ...
Type your GUI toggle hotkey (leave blank for default: "F8"):
modifier_string =
key_string =  F8

GUI toggle hotkey has been set to "F8"
To change the hotkey later, either scroll to the bottom of dynamic_loot_filter.ahk
or re-run this script, and use Ctrl-C to exit after this step.

Step 3: Create your profile
Enter new profile name: Standard

Step 4: Tell DLF where to find and put your filters
Download directory fullpath: **REMOVED**
Download directory verified!
Downloaded filter filename (e.g. "NeversinkRegular.filter"): verystrict.filter
Downloaded filter found!

Now your Path of Exile filters directory
Note: this is not the game install location, but rather the "Documents" location.
This is where your PoE loot filters go, and it should also have a "Screenshots" directory.
Path of Exile filters directory fullpath: **REMOVED**
Path of Exile filters directory verified!

Profile "Standard" created!
Config data saved to "Profiles\Standard.config".
You can edit this file at any time later to update these settings.

Setup complete! Enjoy PoE Dynamic Loot Filter!
Press Enter to close setup.py
```

**Comment by AndreWohnsland** [comment] 2022-06-12 15:50
For anyone else having this issue: Upgrading AHK to the latest version fixed the issue.

Additionally, I noticed you can leave the profile name blank in the setup script, which will cause an error during setup.

**Comment by Apollys** [comment] 2022-06-20 04:26
Yep, the `switch` statement is not supported in old versions of AHK.  Glad you figured it out!

> Additionally, I noticed you can leave the profile name blank in the setup script, which will cause an error during setup.

Thanks for pointing this out.  This is now fixed in the dev branch.

**Closed by Apollys** 2022-06-20 04:27 UTC

**Comment by arnegebert** [comment] 2022-08-18 21:56
I received a very similar error message: 
```
Line Text: case "integer":
Error: This line does not cointain a recognized action.
```

I strongly assume it's the same root cause as I only have AHK version 1.1 installed. 
However, other PoE tools (e.g. [PoB-Item-Tester](https://github.com/VolatilePulse/PoB-Item-Tester#requirements)) frequently require AHK version 1.1. and thus I don't really want to upgrade it. Do you know of a convenient workaround for this or have you considered making the AHK script backwards-compatible with version 1.1? 
Just noting this as feedback, as this extra hurdle makes me a lot less likely to end up using the tool (looks very cool!).
